//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hearts4Kids.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorporateSponsor
    {
        public int Id { get; set; }
        public string WebUrl { get; set; }
        public string LogoUrl { get; set; }
    
        public virtual NewsletterSubscriber NewsletterSubscriber { get; set; }
    }
}
