//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hearts4Kids.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class FundraisingEvent
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime Date { get; set; }
        public string Location { get; set; }
        public string FlyerUrl { get; set; }
        public int PrincipalOrganiserId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
