

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hearts4Kids.Domain
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class Hearts4KidsEntities : DbContext
{
    public Hearts4KidsEntities()
        : base("name=Hearts4KidsEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<AspNetRole> AspNetRoles { get; set; }

    public virtual DbSet<AspNetUser> AspNetUsers { get; set; }

    public virtual DbSet<CorporateSponsor> CorporateSponsors { get; set; }

    public virtual DbSet<FundraisingEvent> FundraisingEvents { get; set; }

    public virtual DbSet<NewsletterSubscriber> NewsletterSubscribers { get; set; }

    public virtual DbSet<Quote> Quotes { get; set; }

    public virtual DbSet<UserBio> UserBios { get; set; }

    public virtual DbSet<QA> QAs { get; set; }

    public virtual DbSet<Receipt> Receipts { get; set; }

}

}

