//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hearts4Kids.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsletterSubscriber
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NewsletterSubscriber()
        {
            this.Receipts = new HashSet<Receipt>();
        }
    
        public int Id { get; set; }
        public string Email { get; set; }
        public DomainConstants.SubscriptionTypes Subscription { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public DomainConstants.Countries Country { get; set; }
        public System.Guid UnsubscribeToken { get; set; }
    
        public virtual CorporateSponsor CorporateSponsor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receipt> Receipts { get; set; }
    }
}
