
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hearts4Kids.Domain
{

using System;
    using System.Collections.Generic;
    
public partial class Receipt
{

    public int Id { get; set; }

    public Nullable<int> NewletterSubscriberId { get; set; }

    public System.DateTime DateReceived { get; set; }

    public System.DateTime DateSent { get; set; }

    public decimal Amount { get; set; }

    public DomainConstants.DonationTypes TransferMethod { get; set; }

    public string Description { get; set; }

    public Nullable<int> UserId { get; set; }



    public virtual AspNetUser AspNetUser { get; set; }

    public virtual NewsletterSubscriber NewsletterSubscriber { get; set; }

}

}
